version: "3.9"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile-dev 
    command: npx nest start --watch 
    container_name: server
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    networks:
      - codeup

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: codeup-dev
    networks:
      - codeup

networks:
  codeup:
    driver: bridge
