version: "3.9"
services:
  server:
    build:
      context: ./
      dockerfile: dockerfile.dev 
    command: npm run start:dev 
    env_file: .env
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - codeup

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: codeup-dev
    networks:
      - codeup

networks:
  codeup:
    driver: bridge
