# Adjust NODE_VERSION as desired
FROM node

# NestJS app lives here
WORKDIR /app

# Install node modules
COPY package.json .

RUN yarn install

# Copy built application
COPY . .

# Start the server by default, this can be overwritten at runtime
EXPOSE 8000 
