version: "3.9"
services:
  server:
    build:
      context: ./
      dockerfile: dockerfile.dev 
    command: yarn start:dev 
    env_file: .env
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/home/node/app
    networks:
      - codeup

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV} 
      POSTGRES_DB: ${DB_NAME_DEV} 
    networks:
      - codeup

networks:
  codeup:
    driver: bridge
