const {
	CLIENT_URL_DEV,
	CLIENT_URL_PROD,
	DB_HOST_DEV,
	DB_PORT_DEV,
	DB_USERNAME_DEV,
	DB_PASSWORD_DEV,
	DB_NAME_DEV,
	DB_HOST_PROD,
	DB_PORT_PROD,
	DB_USERNAME_PROD,
	DB_PASSWORD_PROD,
	DB_NAME_PROD,
	SERVER_HOST_DEV,
	SERVER_HOST_PROD,
	NODE_ENV,
	GITHUB_CLIENT_SECRET,
	GITHUB_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	GOOGLE_CLIENT_ID,
	SERVER_PORT,
	JWT_SECRET,
	DEFAULT_PHOTO_PROFILE,
} = process.env;

const DEV_MODE = NODE_ENV === "development";


const database = {
	DB_PORT: DEV_MODE ? DB_PORT_DEV : DB_PORT_PROD,
	DB_USERNAME: DEV_MODE ? DB_USERNAME_DEV : DB_USERNAME_PROD,
	DB_PASSWORD: DEV_MODE ? DB_PASSWORD_DEV : DB_PASSWORD_PROD,
	DB_NAME: DEV_MODE ? DB_NAME_DEV : DB_NAME_PROD,
	DB_HOST: DEV_MODE ? DB_HOST_DEV : DB_HOST_PROD,
};

const passport = {
	GITHUB_CLIENT_ID,
	GITHUB_CLIENT_SECRET,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
};

const others = {
	SERVER_HOST: DEV_MODE ? SERVER_HOST_DEV : SERVER_HOST_PROD,
	CLIENT_URL: DEV_MODE ? CLIENT_URL_DEV : CLIENT_URL_PROD,
	SERVER_PORT,
	JWT_SECRET,
	DEFAULT_PHOTO_PROFILE,
};

export default { database, passport, others };
